INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (1,"Beach","Sebastian","purus gravida sagittis. Duis gravida. Praesent eu","ABC");
INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (2,"Cooper","Macy","Vivamus euismod","BCD");
INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (3,"Beard","Gray","euismod urna. Nullam lobortis quam a felis ullamcorper","CDE");
INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (4,"Berry","Shoshana","Aliquam","DEF");
INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (5,"Benson","Oren","enim. Nunc ut erat. Sed nunc est,","FGH");
INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (6,"Blanchard","Breanna","ultrices. Duis volutpat nunc sit amet metus.","GHI");
INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (7,"Hodge","Gemma","ullamcorper eu, euismod ac, fermentum vel,","HIJ");
INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (8,"Rodgers","Ingrid","quis diam. Pellentesque","JKL");
INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (9,"Mays","Armand","bibendum. Donec felis orci, adipiscing non, luctus sit amet,","KLM");
INSERT INTO author (authorNum,authorLast,authorFirst,authorBio,pubCode) VALUES (10,"Gordon","Juliet","lorem, sit amet ultricies","LMN");
INSERT INTO bookdetails(bookCode,authorNum,title,price,genre,yearPub,copiesSold,bookDescription) VALUES (1,3,'Book of Gold',23.4,'FIC',2018,5,'lorem ipsum');
INSERT INTO bookdetails(bookCode,authorNum,title,price,genre,yearPub,copiesSold,bookDescription) VALUES (2,1,'Book of Bold',28.4,'SCI',2017,3,'lorem ipsum');
INSERT INTO bookdetails(bookCode,authorNum,title,price,genre,yearPub,copiesSold,bookDescription) VALUES (3,5,'Book of Sold',13.7,'BIO',2016,10,'lorem ipsum');
INSERT INTO bookdetails(bookCode,authorNum,title,price,genre,yearPub,copiesSold,bookDescription) VALUES (4,7,'Book of Told',19.99,'HOR',2015,2,'lorem ipsum');
INSERT INTO users VALUES(1,'rahul','password');
INSERT INTO users VALUES(2,'angelo','password');
INSERT INTO users VALUES(3,'adam','password');
INSERT INTO users VALUES(4,'roly','password');
INSERT INTO users VALUES(5,'kevin','password');
